### ISSUE TITLE
Structure issues

### ISSUE THREAD

**Issue by Romaisaa** [KshitijKarnawat/Structure-from-Motion#4]
Hello Kshitij, Hope you are doing well.
How to use different viewpoints in `depth_nn` ,`generate_point_cloud` ?
How to use the output from `depth_nn` in `generate_point_cloud`?
What is the usage for  `pc_stitching`.py?

I have followed README instructions as follows:
run Calibrate.py and copy resulted matrix into generate_point_cloud
then run pc_stitching. 
The 2 PCD resulted from 2 scripts don't give a proper 3d mesh and gives mesh like this

![image](https://github.com/KshitijKarnawat/Structure-from-Motion/assets/81437926/11d3988f-d783-4a14-9fb7-e88b40783bcc)

**Comment by KshitijKarnawat** [comment]
Hi Romaisaa,

> How to use different viewpoints in depth_nn ,generate_point_cloud ?

Can you please elaborate more on this?

Also can you provide the images that you are trying to stich together as it is really difficult to predict the expected output.

> What is the usage for pc_stitching.py?

This script was used for stitching the point clouds generated using the traditional method (not using deep learning) and comparing the results between the two methods.

**Comment by Hritvik-Choudhari0411** [comment]
How to use the output from depth_nn in generate_point_cloud?

- We're not using the depth map produced by the depth_nn script model in generate_point_cloud, instead, we're going with the OpenCV function to produce a disparity map in the code because we have a stereo camera setup. But you can also obtain depth using a single image through depth_nn as the model is trained for monocular image inputs and then use the obtained depth to generate a point cloud. Hope this helps and let me know if you have any further questions.

**Comment by KshitijKarnawat** [comment]
Closing due to no response
